name = "blog"
main = "dist/_worker.js"
compatibility_date = "2026-02-16"
workers_dev = false

[assets]
directory = "dist"


[observability]
enabled = true

[[routes]]
pattern = "www.justaslime.dev"
custom_domain = true
